- pom.xml
Reverts Alfresco/alfresco-remote-api#18
> Revert "Master"

- src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/admin/support-tools/admin-nodebrowser.get.html.ftl
-  Escaped using JavaScript escaping rules for the action string
> REPO-2981: Security: MNT-18521: Repo Admin console Node Browser vulnerable to reflective XSS

- pom.xml
- src/main/java/org/alfresco/rest/api/impl/QuickShareLinksImpl.java
- src/main/java/org/alfresco/rest/api/model/QuickShareLink.java
- src/test/java/org/alfresco/rest/api/tests/SharedLinkApiTest.java
https://issues.alfresco.com/jira/browse/REPO-2828
Additional fields and allowable operations on target file.
> REPO-2828 more shared link data

- src/main/java/org/alfresco/rest/api/actions/ActionDefinitionsEntityResource.java
- src/main/java/org/alfresco/rest/api/actions/package-info.java
- src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
- src/main/resources/alfresco/public-rest-context.xml
- src/test/java/org/alfresco/rest/api/tests/TestActions.java
- src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
Implements `GET /action-definitions` as per:
https://issues.alfresco.com/jira/browse/REPO-1308
> REPO-1308 retrieve global actions

- src/main/java/org/alfresco/rest/api/actions/ActionExecutionsEntityResource.java
- src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
- src/main/java/org/alfresco/rest/api/model/Action.java
- src/main/resources/alfresco/public-rest-context.xml
- src/test/java/org/alfresco/rest/api/tests/TestActions.java
- src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
- src/test/java/org/alfresco/rest/api/tests/client/data/Action.java
> REPO-1309: Execute an action asynchronously

- src/main/java/org/alfresco/rest/api/Actions.java
- src/main/java/org/alfresco/rest/api/actions/ActionDefinitionsEntityResource.java
- src/main/java/org/alfresco/rest/api/impl/ActionsImpl.java
- src/test/java/org/alfresco/rest/api/tests/TestActions.java
- src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
- implementation and tests for retrieve action definition by id
> REPO-1869: Retrieve action details

- src/main/java/org/alfresco/rest/api/discovery/DiscoveryApiWebscript.java
- src/main/java/org/alfresco/rest/api/model/RepositoryInfo.java
- src/test/java/org/alfresco/rest/api/tests/DiscoveryApiTest.java
> REPO-2372: Add repository ID to the discovery API

- src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- src/main/java/org/alfresco/rest/api/model/PathInfo.java
- src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
- src/test/java/org/alfresco/rest/api/tests/client/data/PathInfo.java
> REPO-1742: Add relativePath property to optional "path" object used for nodes

- src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- src/main/java/org/alfresco/rest/api/model/Node.java
- src/test/java/org/alfresco/rest/api/tests/AbstractBaseApiTest.java
- src/test/java/org/alfresco/rest/api/tests/TestFavourites.java
- src/test/java/org/alfresco/rest/api/tests/client/data/Node.java
Review requirement to support isFavorite as an optional top level property
> REPO-210: Support isFavorite as an optional top level property

- src/main/java/org/alfresco/rest/api/Nodes.java
- src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- src/test/java/org/alfresco/rest/api/tests/TestFavourites.java
added optional isFavorite using parameter INCLUDE_ISFAVORITE.
> REPO-210: added optional param isFavorite.

- src/test/java/org/alfresco/rest/framework/tests/api/mocks/GrassEntityResource.java
- src/test/java/org/alfresco/rest/framework/tests/core/ParamsExtractorTests.java
> REPO-3344: Web Api Parameter `required` is not being used

- pom.xml
Update the postgres driver to 42.2.1
> REPO-3300: Deployment: 6.0 Base Images Stack Alignment

- pom.xml
- src/main/java/org/alfresco/web/app/servlet/AlfrescoX509ServletFilter.java
- src/main/java/org/alfresco/web/app/servlet/CmisSecurityContextCleanerFilter.java
- src/main/java/org/alfresco/web/app/servlet/GlobalLocalizationFilter.java
- src/main/java/org/alfresco/web/app/servlet/KerberosAuthenticationFilter.java
- src/main/java/org/alfresco/web/app/servlet/NTLMAuthenticationFilter.java
- src/main/java/org/alfresco/web/app/servlet/WebScriptSSOAuthenticationFilter.java
- src/main/java/org/alfresco/web/app/servlet/WebscriptCookieAuthenticationFilter.java
- src/main/resources/alfresco/subsystems.Authentication/alfrescoNtlm/ntlm-filter-context.xml
- src/main/resources/alfresco/subsystems.Authentication/alfrescoNtlm/ntlm-filter.properties
- src/main/resources/alfresco/subsystems.Authentication/external/external-filter-context.xml
- src/main/resources/alfresco/subsystems.Authentication/kerberos/kerberos-filter-context.xml
- src/main/resources/alfresco/subsystems.Authentication/kerberos/kerberos-filter.properties
- src/main/resources/alfresco/subsystems.Authentication/passthru/ntlm-filter-context.xml
- src/main/resources/alfresco/subsystems.Authentication/passthru/ntlm-filter.properties
- Moved authentication filter from community-acs-packaging to
remote-api
> REPO-1294: EOL myfaces-api, myfaces-impl & jsp-api

- pom.xml
> REPO-3133: Upgrade commons-email for security issue

- src/main/java/org/alfresco/rest/api/search/impl/SearchMapper.java
- src/test/java/org/alfresco/rest/api/search/SearchMapperTests.java
This Pull Request is a copy of : https://github.com/Alfresco/alfresco-remote-api/pull/85
It was approved already, but I think it is worth to merge this one after bamboo is green
> [MNT-19952] Missing valid includes added (permissions, isLocked) +test

- src/main/java/org/alfresco/rest/api/impl/SitesImpl.java
- src/test/java/org/alfresco/repo/web/scripts/site/SiteServiceTest.java
Delete site fails with 403 for users from SITE_ADMINISTRATORS group.
> REPO-4035:  DELETE /sites/{siteId} fails with 403 

- pom.xml
- src/main/java/org/alfresco/repo/web/scripts/comments/CommentsPost.java
- src/main/java/org/alfresco/rest/api/impl/PeopleImpl.java
- src/main/resources/alfresco/public-rest-context.xml
- src/test/java/org/alfresco/repo/web/scripts/LoginTest.java
- src/test/java/org/alfresco/repo/web/scripts/RepositoryContainerTest.java
- src/test/java/org/alfresco/repo/web/scripts/forms/AbstractTestFormRestApi.java
- src/test/java/org/alfresco/repo/web/scripts/groups/GroupsTest.java
- src/test/java/org/alfresco/repo/web/scripts/person/PersonServiceTest.java
- src/test/java/org/alfresco/repo/web/scripts/quickshare/QuickShareRestApiTest.java
- src/test/java/org/alfresco/repo/web/scripts/rating/RatingRestApiTest.java
- src/test/java/org/alfresco/repo/web/scripts/rule/RuleServiceTest.java
- src/test/java/org/alfresco/repo/web/scripts/subscriptions/SubscriptionServiceRestApiTest.java
- src/test/java/org/alfresco/repo/web/scripts/thumbnail/ThumbnailServiceTest.java
- src/test/java/org/alfresco/repo/web/scripts/transfer/TransferWebScriptTest.java
- src/test/java/org/alfresco/rest/api/tests/TestPeople.java
* Reverted changes from  #110 
* Upgraded data-model and repository (with new fixes)
> REPO-4132: User 'System' cleanup follow-up (Revert changes in REPO-3743)

- pom.xml
- src/main/java/org/alfresco/rest/api/search/SearchSQLApiWebscript.java
- src/main/java/org/alfresco/rest/api/search/model/SearchSQLQuery.java
- src/test/java/org/alfresco/rest/api/search/ResultMapperTests.java
- src/test/java/org/alfresco/rest/api/search/SearchSQLApiWebscriptTests.java
* SEARCH-1351 Add support for filter queries in SQL requests.
* SEARCH-1351 Update repository version to 7.33.13.
(cherry picked from commit 3aa93f5cf20355904484517db81a6f12650b7a8d)
> SEARCH-1351 Add support for filter queries in SQL requests. (#115)

- src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/forms/pickerresults.lib.ftl
- src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/tagging/tag.post.json.ftl
- src/main/resources/alfresco/templates/webscripts/org/alfresco/repository/tagging/tagging.lib.ftl
- Fixed the issue by exposing qnamePath in tag-related FTLs
> SHA-2200 : CLONE MNT-17231 - When a tag newly created is added the tags are not updated in the edit form

- src/main/java/org/alfresco/rest/api/impl/NodesImpl.java
- src/test/java/org/alfresco/rest/api/tests/NodeApiTest.java
Changing cm:name with REST API /nodes/{nodeId} does not update Primary Path
> REPO-4636 [MNT-20863] 

- pom.xml
- src/main/java/org/alfresco/rest/api/Sites.java
- src/main/java/org/alfresco/rest/api/groups/SiteGroupsRelation.java
- src/main/java/org/alfresco/rest/api/impl/SitesImpl.java
- src/main/java/org/alfresco/rest/api/model/SiteGroup.java
- src/main/java/org/alfresco/rest/api/model/SiteMember.java
- src/main/resources/alfresco/public-rest-context.xml
- src/test/java/org/alfresco/rest/api/tests/ApiTest.java
- src/test/java/org/alfresco/rest/api/tests/TestSiteGroups.java
- src/test/java/org/alfresco/rest/api/tests/TestSiteMembers.java
- src/test/java/org/alfresco/rest/api/tests/client/PublicApiClient.java
- src/test/java/org/alfresco/rest/api/tests/client/data/SiteGroup.java
- src/test/java/org/alfresco/rest/api/tests/client/data/SiteMember.java
https://issues.alfresco.com/jira/browse/REPO-5185
https://issues.alfresco.com/jira/browse/REPO-5184
depends on https://github.com/Alfresco/rest-api-explorer/pull/91, https://github.com/Alfresco/alfresco-repository/pull/1041 , https://github.com/Alfresco/rest-api-explorer/pull/92
> [REPO-5184] [REPO-5185] REST API: Add endpoint to expose the groups of a site

- src/test/java/org/alfresco/repo/web/scripts/solr/SOLRWebScriptTest.java
Check that content properties are not included in the /api/solr/nodes endpoint
and properties of type d:any are returned with the appropriate escaping.
> SEARCH-2450 Add tests for JSON escaping in SOLR nodes endpoint.
